# Dev workflow. Performs checks but does NOT release.
# Intended to be run on any pushed development branch (not main).

name: Dev branch checks

on:
  push:
    branches-ignore:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read # To publish a GitHub release.
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Lint
        run: npm run lint
      - name: Clean dist/
        run: npm run clean
      - name: Release (dry-run)
        run: npm run release:dry-run
